import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import CustomLayout from '@/components/custom-layout/customLayout';
import Context from '@/context/context';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className='grid grid-cols-10 justify-between bg-[#ebeef2]'>
          <div className='col-span-1'>
            <CustomLayout />
          </div>
          <div className='col-span-9'>
            <Context>{children}</Context>
          </div>
        </div>
      </body>
    </html>
  );
}
